### ISSUE TITLE
nullable ünlem kullanımı

### ISSUE THREAD

**Issue by cagdaspektas** [VBT-FlutterCamp/yonca_yeprem_calculator#1]
readline içinde ünlem kullanılmış bu kod çalıştırılsa nasıl olur?
isNotEmpty ?? false

**Comment by YoncaYeprem** [comment]
stdin.readLineSync()?.isNotEmpty ?? .... noktalı yere hiçbir şey kabul etmiyor nerede bir yanlışlık var acaba?

**Comment by cagdaspektas** [comment]
@YoncaYeprem şöyle ki 
The argument type 'bool?' can't be assigned to the parameter type 'String' 
double.parse dediğin kısım string istiyor isEmpty ise bool dönüyor sana
o yüzden bu kodu şöyle yazabilirsin:
final double number2 = double.parse(stdin.readLineSync() ?? '');
